name: ESP8266 Auto Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: \~/.platformio
          key: platformio

      - name: Install PlatformIO
        run: pip install --user platformio

      - name: Build Firmware
        run: pio run -e esp8266

      - name: Upload BIN File
        uses: actions/upload-artifact@v4
        with:
          name: ESP8266-Firmware
          path: .pio/build/esp8266/firmware.bin

